name: Docker Build DockerHub Image

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      image:
        description: 'Image Name'
        required: true
        type: string
      tag:
        description: 'Image Tag'
        required: false
        type: string
      target:
        description: 'Dockerfile Target'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      image:
        description: 'Image Name'
        required: true
        type: string
      tag:
        description: 'Image Tag'
        required: false
        type: string
      target:
        description: 'Dockerfile Target'
        type: choice
        required: true
        options:
          - web
          - fpm
          - cli
          - cron

jobs:

  build:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        env:
          REPOSITORY: ${{ env.DOCKERHUB_REPOSITORY }}
          IMAGE_NAME: ${{ inputs.image }}-${{ inputs.target }}
          TARGET: ${{ inputs.target }}
          IMAGE_TAG: ${{ inputs.tag || github.sha }}
        run: |
          cd webapp
          export IMAGE=$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          docker build -t $IMAGE --target $TARGET .
          docker push $IMAGE